const evidenceLabels: Record<string, string> = {
  geometry: "Materielle Fläche",
  logo: "Logo/Signet",
  contact: "Telefonkontakt",
  "page-dominant": "Ganzseitige Fläche",
  "publisher-marking": "Verlagsvermerk „Anzeige“",
  "provenance-uncertain": "Herkunft unklar",
  advertiser: "Werbetreibender",
  typography: "Typografische Gestaltung",
  whitespace: "Freiraum um die Anzeige",
  "positiv:p1a": "P1a Rechtsform",
  "positiv:p1b": "P1b Branchenwort",
  "positiv:p1c": "P1c hervorgehobener Absender",
  "positiv:p2": "P2 Werbeabsicht",
  "positiv:p3": "P3 Kontaktweg",
  "positiv:p4": "P4 Gestaltung",
  "positiv:run50": "Run50: Seitenerkennung und Zuschnittprüfung bestanden",
  "hinweis:traeger": "Hinweis: gemeinnütziger Träger",
  "crop:shortfall": "Rand unter 2,5 mm",
  "veto:ganzseite": "Ablehnung: Ganzseite",
  "veto:behoerde": "Ablehnung: Behörde",
  "veto:kirche": "Ablehnung: Kirche",
  "veto:verein": "Ablehnung: Verein",
  "veto:verzeichnis": "Ablehnung: Verzeichnis",
  "veto:redaktion": "Ablehnung: Redaktion",
  "veto:verlag": "Ablehnung: Verlag",
  "veto:stellenanzeige": "Ablehnung: Stellenanzeige",
  "veto:falscher-ausschnitt": "Ablehnung: Falscher Ausschnitt",
  "fehlend:absender": "Fehlt: Absender",
  "fehlend:werbeabsicht": "Fehlt: Werbeabsicht",
  "fehlend:kontakt": "Fehlt: Kontakt",
  "fehlend:gestaltung": "Fehlt: Gestaltung",
  "unclear:traeger": "Unklar: Träger",
  "unclear:stellenanzeige": "Unklar: Stellenanzeige",
};

export function evidenceLabel(value: string): string {
  return evidenceLabels[value] ?? "Zusätzlicher Prüfbeleg";
}
