from typing import Any, Protocol


class VisionProvider(Protocol):
    def detect_ads(self, image_path: str, page_number: int) -> list[dict[str, Any]]: ...
    def extract_fields(self, crop_path: str) -> dict[str, Any]: ...
    def available(self) -> bool: ...
